### ISSUE TITLE
Create Invoice Confirmations

### ISSUE THREAD

**Issue by qlpqlp** [dogecoinfoundation/gigawallet#106]
Wen sending the confirmations needed to an invoice, it goes always to the default 6 confirmations.

{ "confirmations": 1, "items": [ { "type": "item", "name": "Animal Crossing Nintendo DS", "sku": "69420", "value": 1, "quantity": 1 } ] }

**Comment by tjstebbing** [comment]
the field is **required_confirmations** not **confirmations** :)

**Comment by qlpqlp** [comment]
wow, did not notice that lol, much thanks for pointing that out :)
