### ISSUE TITLE
Payout Stuck

### ISSUE THREAD

**Issue by qlpqlp** [dogecoinfoundation/gigawallet#107]
Wen sending a pay to command, transactions are getting stuck on mempool

`0100000001c6c364f211451835a8a2939eee2e87ef143fe8a161d7b914148337c612e5f52b000000006b48304502210097aa7e681cdd88d59a68d8a8bc780381df368f8d8a086cdb17512f15276ead1502203d2becc69f327273c5ea90206e9cf82bf2d4f891f9aa3c4a1326063c8ee4de0401210388748791fcc0783918ff4e970d89db298bba316cf2e2f25a2965cc6d7458e1f4ffffffff02c09ee605000000001976a914f8e68192379ac91bd725f4e85b1aaa013acffd3688ac70cf0b00000000001976a91435b8c1ddee73f32cc9c552e867ca45475921c3af88ac00000000`

**Comment by tjstebbing** [comment]
Duplicate #85
