### ISSUE TITLE
account affected

### ISSUE THREAD

**Issue by tjstebbing** [dogecoinfoundation/gigawallet#116]
When rescanning the blockchain, 'account was affected' happens after 5-6 blocks on repeat hundreds of times:

2023/09/14 23:09:49 ChainFollower: account was affected: DR4KtYHGyFv3xnN9BfGTTTvb1avusyqj1E (6061)
2023/09/14 23:09:49 ChainFollower: account was affected: DRQu6WR6bpU9N4rm87PvpWZLQSqmGgphFD (6060)

**Comment by raffecat** [comment]
Fixed in commit 180d558292c458c97acf2f5631245e82517106d9
"Fix: only mark unpaid invoices paid (fixes duplicate data)"
