### ISSUE TITLE
Some API need the final slash in the URL

### ISSUE THREAD

**Issue by H7-25** [dogecoinfoundation/gigawallet#128]
referring to the [forum post](https://forum.dogecoin.org/d/14-something-is-malformed-when-attempting-to-generate-invoice/14)
It seems the problem is that some API endpoints need the trailing slash to work, while in the documentation the trailing slash is omitted. I think that for consistency this needs to be corrected.

Example with Invoice creation :

`gigawallet@server:~/gigawallet$ curl -X POST http://localhost:8081/account/dogecoinlab/invoice -H 'Content-Type: application/json' -d '{"required_confirmations":1,"items":[{"type":"item","name":"GigaWallet Test","value":"10.00","quantity":1}]}'

gigawallet@server:~/gigawallet$ curl -X POST http://localhost:8081/account/dogecoinlab/invoice/ -H 'Content-Type: application/json' -d '{"required_confirmations":1,"items":[{"type":"item","name":"GigaWallet Test","value":"10.00","quantity":1}]}'
{"id":"DRzLr3xhAYjKwRjE6fRJTSRKY2nHgNzJF2","items":[{"type":"item","name":"GigaWallet Test","sku":"","description":"","value":"10","quantity":1,"image_link":""}],"created":"2024-02-15T19:50:12.262241281+01:00","total":"10","pay_to_address":"DRzLr3xhAYjKwRjE6fRJTSRKY2nHgNzJF2","required_confirmations":1,"part_payment_detected":false,"total_payment_detected":true,"total_payment_confirmed":false,"payment_unconfirmed":false,"estimate_seconds_to_confirm":0}
`

**Comment by raffecat** [comment]
PR #129  has been merged.
