### ISSUE TITLE
How to build and deploy?

### ISSUE THREAD

**Issue by paulVu** [dogecoinfoundation/gigawallet#46]
Thank you for your efforts. I am enthusiastic about creating a subscription app.
Could you provide guidance on deploying Gigawallet? Additionally, I would appreciate your recommendation on the best cloud platform to use for Gigawallet, preferably one with a one-click deployment option.

**Comment by tjstebbing** [comment]
Hey Paul! GigaWallet is still pre-alpha, we're working toward an initial release in the next week - 10 days.  I plan to create a Docker container for deployment as well as Nix package, which means you should be able to deploy to AWS/GCP/Azure/Your own environment fairly easily. Alternatively if there is a lot of demand we could create a SaaS product with a monthly fee but that's not the main objective, the idea is to get businesses integrating Dogecoin into their systems. Excited to hear more about your subscription app!

**Comment by paulVu** [comment]
Great to hear from you! I really appreciate your focus on getting businesses to integrate Dogecoin into their systems. Regarding the possibility of a SaaS product with a monthly fee, it's great that you're open to exploring that option based on demand.
Keep up the excellent work, and I'm eagerly looking forward to seeing GigaWallet.

**Comment by tjstebbing** [comment]
G'day Paul, we have documentation underway at https://gigawallet.dogecoin.org which covers installation, good luck and let us know how you go !

**Comment by paulVu** [comment]
Thank @tjstebbing awesome work.
