### ISSUE TITLE
Outgoing payment fees too small

### ISSUE THREAD

**Issue by tjstebbing** [dogecoinfoundation/gigawallet#85]
The documentation says that fees are calculated based on txn byte size however we're seeing payments get stuck with miners not accepting them even though their fees are allowable, we should probably start tracking average fee on the network to ensure payments are accepted. 

Here is a stuck txn from @qlpqlp's testing. 
https://dogechain.info/tx/6c4f20969d0bf743ccc8abc4dcc8fe78df00d14bfc08067529db93d755b7f9e7

**Comment by raffecat** [comment]
This was addressed in PR #127 which uses a Core API to estimate current fees, and also uses a minimum fee of 0.01 DOGE.

**Comment by raffecat** [comment]
This was addressed in PR #127  which uses a Core API to estimate current fees, and also uses a minimum fee of 0.01 DOGE.
